language: node_js

node_js:
  - 6
  - 7
  - 8

notifications:
  slack:
    secure: 0eEPiqN/QRgNqoyZmLTGALL4ayPjWSuLc4VTL0QPlLEcPQNII0OoIY+3MR02rkneSKGVBZRukdlWOmi4e7EDZ3aGbm81eZGieFbiVJNPCeMltXiARykLxLjtwTdS1W51pHJHCy0k49MwAyun4ON+SnVpzUADL+7+32eNy6eLjQTWu+9WgTDDgdn31VpysdwdhJp9dcIGSPWCtf4zv4BsIgOxJyQasPt7hsi9kBNYOtfNu7PI44QDXMrBx/sgp1LjU6bOZp6hyE81sdijaZas0XaaJy/6AJ51v4G+54wyu7anL5dnZ9pM06oLeNyHUH71Z7ylhePWp2yB/NqljZjdhu5+SJz42IJ1qj9fz5aoW2bTbGpchJQYOkjjnxkyyzMhhZwRp/YM90laBXOtGFGNMbBszoHUSisrFgG9ZuqwoXdeP9IxoWsPa97wuMZ0IftyOHMLHCf1bJvos2nzzwHKhQ1aLyNmNXcPbe2i8AXSbjfetJubJO9ZwzhrnjAl0iGo+l/NUBRoj64lh7DCVBJd0IgAzKdjIahZbBZGpqCNI7/9MES6yOoXyNruNWjuhn6oUP4xr2Ta1TzyRnOjTX1uogcKZYOgCoPKNUMiBE6/0P6x2jMQWO80OoT3hGSAxFdtyqin09rrJgjcfeThqRs8MgKG+0wgHrk6QsrMmdwUTwo=
